name: params

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string
      build_cmd:
        required: true
        type: string
      test_cmd:
        required: true
        type: string
      matrix:
        required: true
        type: string
        default: 'os=["foo", "bar"]'

env:
  FOO: qwerty

jobs:
  prep:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Matrix
        id: matrix
        run: |
          echo "${{ inputs.matrix }}"
          echo "${{ inputs.matrix }}" >> "$GITHUB_OUTPUT"
  
  compile:
    runs-on: ubuntu-latest
    needs: prep
    strategy:
      fail-fast: false
    steps:
      - name: Build
        run: |
          echo "::echo::on"
          echo "FOO: $FOO"
          echo "FOO: ${{ env.FOO }}"
          echo "make ${{ inputs.build_cmd }}"

  test:
    runs-on: ubuntu-latest
    needs: prep
    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJSON(needs.prep.outputs.matrix) }}
    steps:
      - name: Build
        run: |
          echo "::echo::on"
          echo "os: ${{ matrix.os }}"
         
