name: params

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string
      build_cmd:
        required: true
        type: string
      test_cmd:
        required: true
        type: string
      matrix:
        required: true
        type: string
        #default: "{\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}"
        default: "{\"os\":[\"foo\",\"bar\"]}"

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Build
        run: |
          echo "::echo::on"
          echo "make ${{ inputs.build_cmd }}"

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(inputs.matrix) }}
    steps:
      - name: Build
        run: |
          echo "::echo::on"
          echo "os: ${{ matrix.os }}"
         
