name: params

on:
  workflow_dispatch:
    inputs:
      branch:
        required: true
        type: string
      build_cmd:
        required: true
        type: string
      test_cmd:
        required: true
        type: string
      matrix:
        required: true
        type: string
        default: '{ "os": [ "foo", "bar" ] }'

env:
  FOO: qwerty

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Build
        run: |
          echo "::echo::on"
          echo "FOO: $FOO"
          echo "FOO: ${{ env.FOO }}"
          echo "make ${{ inputs.build_cmd }}"

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(inputs.matrix) }}
    steps:
      - name: Build
        run: |
          echo "::echo::on"
          echo "os: ${{ matrix.os }}"
         
