name: wrapper

on:
  pull_request:

jobs:
  check-description:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check.skip }}
    steps:
    - id: check
    - name: Check description
      run: |
        skip=0
        echo "${{ github.event.pull_request.body }}"
        echo "${{ github.event.pull_request.body }}" | grep "skip ci"
        if [ $? -eq 0 ]; then
          echo "skip build"
          skip=1
        fi
  
  call-workflow-in-another-repo:
    needs: check-description
    if: ${{ needs.check-description.outputs.skip  == 0 }}
    uses: krzycz/demo/.github/workflows/test.yml@main
    with:
      param1: "Hello World!"
