name: wrapper

on:
  pull_request:

jobs:
  check-description:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check.skip }}
    steps:
      - id: check
      - name: Check description
        run: |
          exit 1
