name: pr

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  prep:
    runs-on: ubuntu-latest

    outputs:
      JSON: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - id: set-matrix
        name: Prepare matrix
        run: |
          echo "JSON=\"[ { \"xxx\": 1 }, { \"xxx\": 0 } ]\"" >> "$GITHUB_OUTPUT"
          echo "OUT: "
          cat "$GITHUB_OUTPUT"

  build:
    needs: prep

    runs-on: ubuntu-latest

    strategy:
      matrix: ${{ fromJson(needs.prep.outputs.JSON) }}

    steps:
      - name: Build it
        run: |
          echo "XXX=${{ matrix.xxx }}"
