name: wrapper

on:
  pull_request:

jobs:
  check-description:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check.skip }}
    steps:
    - id: check
    - name: Check description
      run: |
        skip=0
        echo "${{ github.event.pull_request.body }}"
        echo "${{ github.event.pull_request.body }}" | grep "skip ci"
        if [ $? -eq 0 ]; then
          echo "skip build"
          skip=1
        fi
  
  build:
    needs: check-description
    runs-on: ubuntu-latest
    if: ${{ needs.check-description.outputs.skip  == 0 }}
    steps:
    - id: bld
    - name: Build
      run: |
        echo "Hello world!"
      
