name: pr2

on:
  pull_request:

jobs:
  xxx:
    runs-on: ubuntu-latest

    env:
      pr_body: ${{ github.event.pull_request.body }}

    steps:
      - name: Check
        run: |
          echo "::echo::on"
          echo "PR: ${{ env.pr_body }}"
          echo "${{ env.pr_body }}" | grep "skip ci"
          if [ $? -eq 0 ]; then
            echo "skip"
            skip=1
            return 0
          else
            return 0
          fi

      - name: Check2
        run: |
          echo "::echo::on"
          echo "PR: ${{ env.pr_body }}"
