name: rerun

on:
  workflow_run:
    types:
      - completed

jobs:
  rerun_failed_jobs:
    runs-on: [ ubuntu-latest ]
    if: ${{ github.event.workflow_run.run_attempt == "1" }}
    steps:
      - name: foo
        run: |
          echo "::echo::on"
          curl -L -n -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/rerun-failed-jobs
