name: reusable

on:
  workflow_dispatch:
    inputs:
      param1:
        required: true
        type: string
        
  workflow_call:
    inputs:
      param1:
        required: true
        type: string

  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test1
        run: |
          echo "reusable: ${{ inputs.param1 }}"
    
